import React from "react";

export const CONTENT = {
  COLLECTION: {
    HEADER: `Collection`,
    BODY: (
      <>
        <b>'Processed Feed'</b> is a series comprising <b>16 unique artworks</b>
        created by <b>Snoozed Sneeze</b>. Each piece is a <b>1/1 NFT</b>
        featuring an <b>audiovisual interpolation</b> created to explore the
        various <b>elements</b> that consistently contribute to his creative
        process, through <b>individual gems</b> and their idiosyncratic phases
        of <b>refinement</b>. This work captures the
        <b>transformation of raw ideas</b> through <b>6</b> stages, reflecting
        the taming of wild concepts into refined applicable forms.
      </>
    ),
    FOOTER: [
      <p>
        (Please scroll down the page to find a schedule for collector-votes and
        airdrops showing the essential timeline that this collection will be
        created over. You shall also find the grid size mentioned alongside. )
      </p>,
    ],
  },
  PROCESS: {
    HEADER: `Process`,
    BODY: (
      <>
        Committed to creating art that was <b>challenging to think about</b> and
        just as <b>easy to create</b>, he utilized leading early stage AI tools
        like <b>Midjourney</b>, <b>RunwayML</b>, <b>Topaz</b> and <b>ChatGPT</b>
        . Technique is craft, not art, in his view. Additionally, he
        collaborated with a Romanian composer named <b>Ana Maria Oancea</b> who
        contributed <b>unique soundtracks</b> for each animation based on{" "}
        <b>prompts</b>, thereby furthering the <b>primitive idea</b> closer to
        fruition. The duration of each animation is <b>60 seconds</b>. While AI
        served as a <b>tool</b>, the musician became a <b>collaborator</b>,
        highlighting the{" "}
        <b>interplay between programmatic and natural language.</b>
        <b>Accessible</b> captions for visuals are the norm in our times, often
        expository or poetic for dramatic effect. Therefore each piece extends
        itself to the receiver through <b>poetry</b> generated by <b>ChatGPT</b>{" "}
        which is further <b>tuned to SNZ's preference</b> based on its{" "}
        <b>proximity to his vision</b>.
      </>
    ),
    FOOTER: [],
  },
  ARTIST: {
    HEADER: `Artist`,
    BODY: (
      <>
        <b>Snoozed Sneeze (SNZ)</b> , is a <b>reactionary artist</b> from{" "}
        <b>Mumbai, India</b>. His work largely focuses on the <b>intangible</b>{" "}
        as he adopts and aborts various ways to communicate the same.
        <b>Inadequate autonomy</b> pulled him away from architecture and design
        earlier on. <b>Scale</b>, <b>composition</b> and <b>materiality</b>{" "}
        informing his method, he transitioned to art through a few years of
        mural-making and street art along the western coast and a few Himalayan
        valleys in India. The flame of democratizing art burned bright within
        him, while he worked with NGOs in painting street art for slum areas,
        local police headquarters, as well as co-creating what was considered
        the third longest street art in India at the time in 2017 (300ft x 15ft)
        for Reliance at the Mumbai Metro rail yard. SNZ's most recent NFT
        release has been his series named <b>Butterfly Bubble</b> (2022).
        Inspired by <b>temporal themes</b>, SNZ’s earlier work tokenized as
        NFTs, speaks to the inevitability of time (<b>‘Patients of Time’</b> -
        April 2021), identifying ourselves (<b>‘OG SUGGA’</b> September 2020,
        <b>‘Epigenetics’</b> - April 2021) and acknowledging our dissonance as
        we spin up our webs of perception and find ourselves trapped within them
        (<b>‘RISKY BIZKITS’</b> - September 2020, <b>‘MiNES FOR MiNDS’</b> -
        December 2021).
      </>
    ),
    FOOTER: [
      `It was also when I adopted the pseudonym ‘Snoozed Sneeze’ as it is medically detrimental to snooze sneezes - just as being untruthful or holding back is. Few other human reactions are as genuine as a sneeze.`,
      `I felt like I’d been snoozed on several occasions and longed for honest discourse.`,
    ],
  },
  VISION: {
    HEADER: `Vision`,
    BODY: (
      <>
        SNZ believes that his <b>art's identity</b> arises from his{" "}
        <b>creation process</b> rather than the nature of the{" "}
        <b>final output</b>. He intends for each piece to express the{" "}
        <b>shared importance</b> of each element, however unsettling or
        comforting it is, to be <b>worked through</b> and <b>not around</b>. The
        ongoing debate over the <b>implications of the use of AI in art</b>: its
        role as a <b>tool and/or collaborator</b> offers an unstable stool to
        place our bets upon and SNZ is betting on both sides by making this
        statement.
        <b>Deliberation defies all doubts.</b>
      </>
    ),
    FOOTER: [],
  },
  JOURNEY: {
    HEADER: `JOURNEY`,
    BODY: (
      <>
        These <b>gems' evolution</b> is depicted through an increasing number of
        stages in <b>60-second long interpolations</b>, tokenized and{" "}
        <b>unfolding over time</b> on the <b>Ethereum blockchain</b> (based on{" "}
        <b>ascertained block timestamps</b>).
      </>
    ),
    FOOTER: [],
  },
};
