import React from "react";

export const CONTENT = {
  COLLECTION: {
    HEADER: `Collection`,
    BODY: (
      <>
        <p>
          <b>'Processed Feed'</b>, is a series comprising 16 unique artworks
          created by Snoozed Sneeze. Each piece is a 1/1 NFT featuring a
          60-second audiovisual interpolation created to explore the various
          elements that consistently contribute to his creative process, through
          individual gems and their idiosyncratic phases of refinement. This
          work captures the transformation of raw ideas through 6 stages,
          reflecting the taming of wild concepts into refined applicable forms.
        </p>
      </>
    ),
    FOOTER: [
      <p>
        (Please scroll down the page to find a schedule for collector-votes and
        airdrops showing the essential timeline that this collection will be
        created over. You shall also find the grid size mentioned alongside. )
      </p>,
    ],
  },
  PROCESS: {
    HEADER: `Process`,
    BODY: (
      <>
        <p>
          Committed to creating art that was challenging to think about and just
          as easy to create, he utilized leading early stage AI tools like
          Midjourney, RunwayML, and ChatGPT. Technique is technically the craft
          and not art, in his view.
        </p>
        <p>
          Additionally, he collaborated with a Romanian music composer named Ana
          Maria Oancea who contributed unique soundtracks for each animation
          based on prompts, thus furthering the primitive idea closer to
          fruition.
        </p>
        <p>
          While AI served as a tool, the musician became a collaborator,
          highlighting the interplay between programmatic and natural language.
        </p>
        <p>
          Accessible captions for visuals are the norm in our times, often
          expository or poetic for dramatic effect. Therefore each piece extends
          itself to the receiver through poetry generated by ChatGPT which is
          further tuned to SNZ's preference based on its proximity to his
          vision.
        </p>
      </>
    ),
    FOOTER: [],
  },
  ARTIST: {
    HEADER: `Artist`,
    BODY: (
      <>
        <p>
          {" "}
          <b>Snoozed Sneeze (SNZ) </b>, is a <b>reactionary artist </b>from
          Mumbai, India. His work largely focuses on the <b>intangible </b> as
          he adopts and aborts various ways to communicate the same.
        </p>
        <p>
          Inadequate autonomy pulled him away from design earlier on. Scale,
          composition and materiality informing his method, he transitioned to
          art through a few years of mural-making and street art along the
          western coast and a few Himalayan valleys in India. The flame of
          democratizing art burned bright within him, while he worked with NGOs
          in painting street art for slum areas, local police headquarters, as
          well as co-creating what was considered the third longest street art
          in India at the time in 2017 (300ft x 15ft) for Reliance at the Mumbai
          Metro rail yard.
        </p>
        <p>
          SNZ's most recent NFT release has been his series named Butterfly
          Bubble. Inspired by temporal themes, SNZ’s earlier work tokenized as
          NFTs, speaks to the inevitability of time (‘Patients of Time’ - April
          2021), identifying ourselves (‘OG SUGGA’ September 2020,‘Epigenetics’
          - April 2021) and acknowledging our dissonance as we spin up our webs
          of perception and find ourselves trapped in them (‘RISKY BIZKITS’ -
          September 2020, ‘MiNES FOR MiNDS’ - December 2021).
        </p>
        {/* <p>
          Painting these walls as <b>massive canvasses</b> was fundamental to
          the <b>maturation</b> of SNZ’s art practice{" "}
          <b>without compromising his innocence</b> in confronting ideas in a
          playful manner. His <b>visual vocabulary</b> reflects various{" "}
          <b>gradients</b> and <b>textures</b> from the{" "}
          <b>vastness of seas, fields</b> and <b>valleys</b> stippled with
          intricate forms of <b>flowers, butterflies, birds</b> and{" "}
          <b>people</b>. Since childhood, he was curious about{" "}
          <b>metamorphosis</b> and the <b>complete disintegration</b> that a
          butterfly goes through as it evolves from a pupa. It offered him
          flexibility growing up in{" "}
          <b>
            disintegrating and reintegrating his conviction from time to time.
          </b>
        </p>
        <p>
          In <b>July 2020</b> SNZ collected his first NFT by an artist named{" "}
          <b>NFN Kalyan</b> whom he credits for playing a pivotal role in his
          creative journey. Anticipating a <b>paradigm shift</b>, words such as{" "}
          <b>
            ambition, innovation, collaboration, autonomy, longevity,
            transparency
          </b>{" "}
          and such framed the foundation for the early conversation about{" "}
          <b>decentralized creation.</b> It was also when he adopted the
          pseudonym <b>‘Snoozed Sneeze’</b> as it is medically detrimental to
          snooze a sneeze - akin to <b>withholding truth</b>. Few other human
          reactions are as genuine than a sneeze. He longs for{" "}
          <b>honest discourse </b> through his work.
        </p>*/}
        <p>
          {" "}
          <b>‘Time’ </b> plays an intriguing role in the overarching
          decentralized experience and in creation. Through SNZ’s earlier work
          tokenized as NFTs, he dabbles with ideas such as the{" "}
          <b>inevitability of time </b> (<b>‘Patients of Time’ </b>- April
          2021), <b>identifying ourselves </b> (<b>‘OG SUGGA’</b> September
          2020,
          <b>‘Epigenetics’ </b>- April 2021) and{" "}
          <b>acknowledging our dissonance </b> as we spin up our webs of
          perception and find ourselves trapped in them (<b>‘RISKY BIZKITS’</b>{" "}
          - September 2020, <b>‘MiNES FOR MiNDS’</b> - December 2021).
        </p>
      </>
    ),
    FOOTER: [
      `It was also when I adopted the pseudonym ‘Snoozed Sneeze’ as it is medically detrimental to snooze sneezes - just as being untruthful or holding back is. Few other human reactions are as genuine as a sneeze.`,
      `I felt like I’d been snoozed on several occasions and longed for honest discourse.`,
    ],
  },
  VISION: {
    HEADER: `Vision`,
    BODY: (
      <>
        <p>
          SNZ believes that his art's identity arises from his creation process
          rather than the nature of the final product. He intends for each piece
          to express the shared importance for each process, however trying or
          comforting, to be worked through and not around. The ongoing debate
          over the implications of the use of AI in art: its role as a tool
          and/or collaborator offers an unstable stool to place our bets upon
          and SNZ is betting on both sides.
        </p>
        <p>Deliberation defies all doubts.</p>
      </>
    ),
    FOOTER: [],
  },
  JOURNEY: {
    HEADER: `JOURNEY`,
    BODY: (
      <>
        <p>
          The gems' evolution is depicted through increasing stages in 60-second
          long interpolations, tokenized and unfolding over time on the Ethereum
          blockchain (based on ascertained block numbers).
        </p>
      </>
    ),
    FOOTER: [],
  },
};
